[build]
  command = "npm run build"
  publish = ".next-build"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_API_URL = "https://city-mall-smart-locker-api.onrender.com/api"
  NEXT_PUBLIC_SOCKET_URL = "https://city-mall-smart-locker-api.onrender.com"
